### ISSUE TITLE
Modify Dashboard

### ISSUE THREAD

**Issue by HanielDiaz** [SHPEUCF/shpeucfapp#38]
### To-Do
_Dashboard must have useful features such as seeing latest announcement and seeing general SHPE News. Its basis should be that of a welcoming interface where users can see how they can be more active in SHPE and have direct access to the resources provided._

- [x] **Display committees of SHPE**. (How to get more involved...)
Not only will this list the committees SHPE currently has, but also link to these committees within the app. For that reason, it should implemented in a List, so that we don't have to worry about future committees being added. Will be present in the app once the committee system has been implemented.
- [ ] **Inform members of resume upload**.
- [x] **Improve styling**.
This will be implemented as part of the AppStyling branch, currently being worked on by @csepulveda7.
- [x] **Add upcoming events at the top of the dashboard**.
This will be dynamic since events will continuously be added/removed/edited. Events should be neatly placed so that a user can see some of the most recent events.

- [x] **Display top people in the leaderboard**.
Should also be dynamic and link to the Leaderboard screen in case they want to see their position on the Leaderboard relative to other members' points.
_Update (3/22/19)_: Although it correcly goes to the Leaderboard screen, it doesn't go back to Dashboard upon return (goes back to the More screen), something that should be fixed on Leaderboard.

- [x] **Add button that links to Slack**.
It should prompt the user to open the link in the Slack app.
_Update (3/22/19)_: Right now it links to the workspace on the Slack website. The goal is to have it open automatically if the user has the Slack app. Otherwise, it should open on the web browser as it does now.

**Comment by AgentIMR** [comment]
- Events styling was updated to add description but only allow a portion of it.
- TouchableOpacity exists but links to nothing. Should be made to it goes to the event details of the current event shown, if any.
- Committees was added as placeholder with a "Coming Soon" label. Should be added soon so that users can go to each individual committee. May add some additional capabilities to provide more useful information right on the dashboard.

**Comment by joshncs22** [comment]
A tentative list of short-term goals for the development of the dashboard would include

**- create a list of committees and descriptions with contact info as a placeholder for something more detailed
- discover methods of app integration via Instagram and Slack
 - include a system for resume upload via google docs**

**Comment by idelmr** [comment]
Fixed by @esteban737 last year
